---

- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Assure argocd is installed
    kubernetes.core.helm:
      name: argocd
      chart_repo_url: "https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd"
      chart_ref: argocd
      release_namespace: default
      release_state: present
    register: result
  - name: Assure argocd is installed
    ansible.builtin.assert:
      that: 
      - result.status.status == "deployed"